# config.properties
# Default configuration for the Web Page Analyzer

# --- HTTP Server ---
http.port=8080
http.shutdown.timeout=120s

# --- JWT ---, this is not using right now
jwt.secret=my-user-1
jwt.token.ttl=100h

# --- Rate Limiter ---
rate.limiter.rps=30
rate.limiter.burst=60

# --- Middleware ---
idempotency.ttl=5s

# --- Services ---
fetcher.timeout=30s
link.checker.timeout=60s

# --- Logging ---
logger.level=debug